ignore:
    - "**/BarGraph.java"
    - "**/CreateAccountValidation.java"
    - "**/MainActivityValidation.java"
    - "**/LogAnalytics.java"
    - "**/LogEntry.java"
    - "**/OurLog.java"
    - "**/ProduceItem.java"
    - "**/ProfileActivity.java"
    - "**/RecyclerViewAdapterLog.java"
    - "**/User.java"
    - "**/PieGraph.java"
    - "**/LogEntryHome.java"
    
