ignore:
  - "**/CreateAccountValidation.java"
  - "**/MainActivityValidation.java"
  - "**/LogAnalytics.java"
  - "**/LogEntry.java"
  - "**/OurLog.java"
  - "**/ProduceItem.java"
  - "**/RecyclerViewAdapterLog.java"
  - "**/User.java"
  - "**/PieGraph.java"
  - "**/BarGraph.java"
  - "**/LogEntryHome.java"
  - "**/BarGraphValidation.java"
  - "**/PieGraphValidation.java"