ignore:
  - "**/CreateAccountValidation.java"
  - "**/MainActivityValidation.java"
  - "**/LogAnalytics.java"
  - "**/LogEntry.java"
  - "**/OurLog.java"
  - "**/ProduceItem.java"
  - "**/RecyclerViewAdapterLog.java"
  - "**/User.java"
  - "**/PieGraph.java"
  - "**/BarGraph.java"
  - "**/BarGraphValidation.java"
  - "**/PieGraphValidation.java"
  - "**/SentInvite.java"
  - "**/AddFriends.java"
  - "**/FriendsAdapter.java"
  - "**/GotInvite.java"
  - "**/OutboxAdapter.java"
  - "**/InboxAdapter.java"
  -